const API_KEY = "of40zatnkd1ftcaqnf92ahqznkg1vn";

const BROADCAST_LANGUAGE = [
  { id: "ja", name: "日本語" },
  { id: "en", name: "English" },
  { id: "id", name: "Bahasa Indonesia" },
  { id: "ca", name: "Català" },
  { id: "da", name: "Dansk" },
  { id: "de", name: "Deutsch" },
  { id: "es", name: "Español" },
  { id: "fr", name: "Français" },
  { id: "it", name: "Italiano" },
  { id: "hu", name: "Magyar" },
  { id: "nl", name: "Nederlands" },
  { id: "no", name: "Norsk" },
  { id: "pl", name: "Polski" },
  { id: "pt", name: "Português" },
  { id: "ro", name: "Română" },
  { id: "sk", name: "Slovenčina" },
  { id: "fi", name: "Suomi" },
  { id: "sv", name: "Svenska" },
  { id: "tl", name: "Tagalog" },
  { id: "vi", name: "Tiếng Việt" },
  { id: "tr", name: "Türkçe" },
  { id: "cs", name: "Čeština" },
  { id: "el", name: "Ελληνικά" },
  { id: "bg", name: "Български" },
  { id: "ru", name: "Русский" },
  { id: "uk", name: "ภาษาไทย" },
  { id: "zh", name: "中文" },
  { id: "zh-hk", name: "粵語" },
  { id: "ko", name: "한국어" },
  { id: "asl", name: "American Sign Language" },
  { id: "other", name: "その他" },
] as const;

export const TWITCH_CONSTANTS = {
  BROADCAST_LANGUAGE,
  API_KEY,
};
